smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -334,6 +334,59 @@ jobs:
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
+  smoke-test:
+    docker:
+      - image: alpine:latest
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [ backend-build ]
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache nodejs npm aws-cli curl
+      - run:
+          name: Backend smoke test
+          command: |
+            export EC2_INSTANCE_ID=$(aws cloudformation describe-stack-resources \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query "StackResources[?ResourceType=='AWS::EC2::Instance'].PhysicalResourceId" \
+              --output text)
+
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --instance-ids $EC2_INSTANCE_ID \
+              --query "Reservations[0].Instances[0].PublicIpAddress" \
+              --output text)
+              
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL: $API_URL"
+            
+            if curl "${API_URL}/api/status" | grep -q "ok"
+            then
+              echo "Backend smoke test passed."
+            else
+              echo "Backend smoke test failed."
+              exit 1
+            fi
+      - restore_cache:
+          keys: [ frontend-build ]
+      - run:
+          name: Frontend smoke test
+          command: |
+            export URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s "${URL}" | grep -q "Welcome"
+            then
+              echo "Frontend smoke test passed."
+            else
+              echo "Frontend smoke test failed."
+              exit 1
+            fi
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
 workflows:
   default:
     jobs:
@@ -360,3 +413,5 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
